trigger: 'none' # will disable CI builds entirely

pool:
  vmImage: 'windows-2019'
    
variables:
  BuildConfiguration: release
  
steps:

- task: UseDotNet@2
  displayName: Install .NET 6 sdk
  inputs:
    packageType: sdk
    version: 6.0.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: Restore Nuget Packages
  inputs:
    azureSubscription: 'azure-cli-2024-10-14-06-24-51'
    command: 'restore'
    projects: '**/WebApp.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: Build Web App
  inputs:
    azureSubscription: 'azure-cli-2024-10-14-06-24-51'
    command: 'build'
    projects: '**/WebApp.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Run Unit Tests
  inputs:
    azureSubscription: 'azure-cli-2024-10-14-06-24-51'
    command: 'test'
    projects: '**/*UnitTest*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Create Web App Package (.zip)
  inputs:
    azureSubscription: 'azure-cli-2024-10-14-06-24-51'
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact (WebApp.zip)'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
